### ISSUE TITLE
Locations parameters

### ISSUE THREAD

**Issue by ki9us** [wrapi/square#1]
The API doesn't seem to consider the `location_id` parameter, which is required for [most endpoints](https://docs.connect.squareup.com/api/connect/v1/#endpointpaths).

**Comment by ki9us** [comment]
Thanks for making this, by the way.  I was just about to make my own.

**Comment by palanik** [comment]
@keith24 Thank you for checking this out.

Yes, you are correct that `location_id` is required for most endpoints.
Actually, the parameter is supported by its former name - `merchant_id` in this library. 

Apparently, Square updated the docs to call it `location_id` later, after I published mine to npm. 
If you look carefully, you'll see it is still referred as `merchant_id` in some places.
eg. https://docs.connect.squareup.com/api/connect/v1/#navsection-variations

I will update the docs in the repo.

Currently, working on v2. Check back later.

**Comment by palanik** [comment]
More details on API change: https://docs.connect.squareup.com/articles/connect-api-changes-2016-02/

**Comment by palanik** [comment]
@keith24 I've updated the docs & pushed version 0.2.0.

You can use the API two ways:
1. For a specific location.
   
   >  If you have the location id, create the client object with the location id.
   > 
   > `var client = new squareWrapi('v1', API_ACCESS_TOKEN, LOCATION_ID);`
   > 
   > square-wrapi will use this location id. on calls that require location id.
2. For all locations.
   
   > Create the client object without location id.
   > 
   > `var client = new squareWrapi('v1', API_ACCESS_TOKEN);`
   > 
   > Provide `location_id` as the first parameter to all the calls that require location id.

Thanks.
